version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    groups:
      spring:
        patterns:
          - "org.springframework:*"
      azure-sdk:
        patterns:
          - "com.azure:*"
      test-dependencies:
        patterns:
          - "org.junit*:*"
          - "org.mockito:*"
      maven-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "io.spring.javaformat:*"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    groups:
      github-actions:
        patterns:
          - "*"
